#pragma once

#define WINDOW_WIDTH 150
#define WINDOW_HEIGHT 40

#define OVEN_NOT_PURCHASED 0
#define OVEN_AVAILABLE 1
#define OVEN_BUSY 2

#define COOK_NOT_PURCHASED 0
#define COOK_AVAILABLE 1
#define COOK_BUSY 2